display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-tmc-centralnode-mid
telescope: SKA-mid

subarray_count: 1
dishes: ["01"]

labels:
  app: ska-tmc-centralnode-mid

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  retry:
  - "--tries=10"
  - "--sleep=5"

dsconfig:
  configuration_file: data/configuration.json
  timeout: 300s
  image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.1
      pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.5
    pullPolicy: IfNotPresent


centralnodemid:
  image:
    registry: artefact.skao.int
    image: ska-tmc-centralnode-mid
    tag: 0.3.1
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi

deviceServers:
  leafs:
    enabled: false
    instances: ["01"]
    file: "data/leafs.yaml"

  subarrays:
    enabled: false
    instances: ["01"]
    file: "data/subarrays.yaml"

  centralnode:
    enabled: true
    instances: ["01"]
    file: "data/centralnode.yaml"
    CspMasterLeafNodeFQDN: "ska_mid/tm_leaf_node/csp_master"
    CspMasterFQDN: "mid_csp/elt/master"
    SdpMasterLeafNodeFQDN: "ska_mid/tm_leaf_node/sdp_master"
    SdpMasterFQDN: "mid_sdp/elt/master"
    subarray_count: 1
    DishLeafNodePrefix: "ska_mid/tm_leaf_node/d"
    NumDishes: 1


nodeSelector: {}

affinity: {}

tolerations: []
