"""
This file is part of the CentralNode project and defines variables used
"""

# ENUMS
from enum import IntEnum, unique

@unique
class ModesAvailability(IntEnum):
    not_available = 0
    available = 1

# In/Out command constants
CMD_SET_STOW_MODE = "SetStowMode"
CMD_SET_STANDBYLP_MODE = "SetStandbyLPMode"
CMD_SET_STANDBYFP_MODE = "SetStandbyFPMode"
CMD_SET_OPERATE_MODE = "SetOperateMode"
CMD_ASSIGN_RESOURCES = "AssignResources"
CMD_RELEASE_RESOURCES = "ReleaseAllResources"
CMD_STANDBY = "Standby"
CMD_TELESCOPE_ON = "TelescopeOn"
CMD_ON = "On"
CMD_OFF = "Off"
CMD_TELESCOPE_STANDBY = "TelescopeStandBy"
CMD_TELESCOPE_OFF = "TelescopeOff"
STR_CMD_STANDBY_DISH = "STANDBY command invoked on Dish devices"
STR_CMD_STANDBY_CSP_DEV = "STANDBY command invoked on CspMasterLeafNode device "
STR_CMD_STANDBY_SDP_DEV = "STANDBY command invoked on SdpMasterleafNode device "
STR_CMD_STANDBY_SA_DEV = "STANDBY command invoked on SubarrayNode device"
STR_CMD_TELESCOPE_OFF_DISH = "TelescopeOff command invoked on Dish devices"
STR_CMD_TELESCOPEON = "TelescopeOn command invoked on Dish devices"
STR_CMD_TELESCOPESTANDBY = "TelescopeStandby command invoked on Dish devices"
STR_CMD_ON_DISH = "ON command invoked on Dish devices"


# Event messages
EVT_UNKNOWN = "Event from the Unknown device!"
EVT_SUBSR_HEALTH_STATE = "healthState"
EVT_SUBSR_OBS_STATE = "obsState"
EVT_SUBSR_STATE = "State"


# Error messages
ERR_AGGR_OBS_STATE = "Error in Subarray obsState callback \n"
ERR_SUBSR_SA_HEALTH_STATE = "Error in subscribing Subarray healthState \n"
ERR_SUBSR_SA_OBS_STATE = "Error in subscribing Subarray obsState \n"
ERR_SUBSR_CSP_MASTER_HEALTH = "Error in subscribing CSP Master healthState \n"
ERR_SUBSR_SDP_MASTER_HEALTH = "Error in subscribing SDP Master healthState \n"
ERR_SUBSR_CSP_MASTER_LN_STATE = "Error in subscribing CSPMasterLeafNode State \n"
ERR_SUBSR_SDP_MASTER_LN_STATE = "Error in subscribing SDPMasterLeafNode State \n"
ERR_SUBSR_CSP_SA_LN_STATE = "Error in subscribing CSPSubarrayLeafNode State \n"
ERR_SUBSR_SDP_SA_LN_STATE = "Error in subscribing SDPSubarrayLeafNode State \n"
ERR_SUBSR_DISH_LN_STATE = "Error in subscribing DishLeafNode State \n"
ERR_SUBSR_SA_STATE = "Error in subscribing TM Subarray State \n"
ERR_INIT_PROP_ATTR_CN = "Error on initialising properties and attributes on Central Node device."
ERR_IN_READ_DISH_LN_DEVS = "Error in reading exported Dish Leaf Node device names from database \n"
ERR_IN_CREATE_PROXY = "Error in creating proxy of the LeafNode device: "
ERR_EXE_STOW_CMD = "Error in executing STOW command "
ERR_EXE_STANDBY_CMD = "Error in executing STANDBY Telescope command "
ERR_EXE_TMC_STANDBY_CMD = "Error in executing TMC STANDBY command "
ERR_EXE_TELESCOPE_STANDBY_CMD = "Error in executing TELESCOPE STANDBY command "
ERR_EXE_TELESCOPE_OFF_CMD = "Error in executing TelescopeOff command "
ERR_EXE_OFF_CMD = "Error in executing OFF Telescope command "
ERR_EXE_TMC_ON_CMD = "Error in executing TMC ON command "
ERR_IN_DESIRED_STATE_ATTR =" Error in Updating Desired Telescope State attribute. "

ERR_EXE_ON_CMD = "Error in executing TelescopeOn(ON) Telescope command "
ERR_INVALID_JSON = "Invalid JSON format"
ERR_JSON_KEY_NOT_FOUND = "JSON key not found "
ERR_RELEASE_RESOURCES_CMD = "Error occured while releasing resources "
ERR_SUBARRAY_HEALTHSTATE = "Key Error occurred while setting Subarray healthState"
ERR_ASSGN_RESOURCES = "Error occurred while assigning resources to the Subarray \n"
ERR_RELEASE_RESOURCES = "Error occurred while releasing resources from the Subarray \n"
ERR_STOW_ARGIN = "Invalid StowAntennas arguments \n"
ERR_HEALTH_STATE_CB = "Error handling healthState callback for evt: %s"
ERR_RECEPTOR_ID_REALLOCATION = "The following Receptor id(s) are allocated to other subarrays: "
ERR_DEVFAILED_MSG = "This is error message for devfailed"
ERR_SUBARRAY_ID_DOES_NOT_EXIST = "The Subarray '99' does not exist."

# General strings
STR_HEALTH_STATE = "healthState of "
STR_STATE = "state of "
STR_OK = " :-> OK"
STR_DEGRADED = " :-> DEGRADED"
STR_FAILED = " :-> FAILED"
STR_UNKNOWN = " :-> UNKNOWN"
STR_ON = " :-> ON"
STR_OFF = " :-> OFF"
STR_INIT = " :-> INIT"
STR_FAULT = " :-> FAULT"
STR_HEALTH_STATE_UNKNOWN_VAL = "Subarray healthState event returned unknown value \n"
STR_ERR_MSG = "Error message is: "
STR_STOW_CMD_ISSUED_CN = "STOW command invoked from Central node on the requested dishes"
STR_TELESCOPE_OFF_CMD_ISSUED = "TelescopeOff command invoked from Central node"
STR_TMC_OFF_CMD_ISSUED = "TMC OFF command invoked from Central node"
STR_TMC_ON_CMD_ISSUED = "TMC ON command invoked from Central node"
STR_ON_CMD_ISSUED = "TelescopeOn (ON) command invoked from Central node"
STR_TMC_STANDBY_CMD_ISSUED = "TMC STANDBY command invoked from Central node"
STR_TELESCOPE_STANDBY_ISSUED = "TELESCOPE STANDBY command invoked from Central node"
STR_ON_CMD_ISSUED = "TelescopeOn command invoked from Central node"
STR_INIT_SUCCESS = "CentralNode is initialized successfully."
STR_FALSE = "False"
STR_DISH_DUPLICATE = "List of the dishes that are already allocated: "
STR_ASSIGN_RESOURCES_SUCCESS = "Resources are assigned successfully"
STR_FALSE_TAG = "False in ReleaseALL tag is not yet supported"
STR_REL_RESOURCES = "Resources have been released successfully"
STR_ALL_RES_NOT_REL = "All the resources are not released"
STR_LIST_RES_NOT_REL = "List of the resources that are not released:"
STR_CSP_CBF_DEV_NAME = "mid_csp_cbf/sub_elt/master"
STR_CMD_FAILED = "CentralNode_CommandFailed"
STR_STOW_ANTENNA_EXEC = "STOW_ANTENNAS command execution"
STR_RELEASE_RES_EXEC = "RELEASERESOURCES command execution"
STR_ASSIGN_RES_EXEC = "ASSIGNRESOURCES command execution"
STR_TELESCOPE_OFF_EXEC = "TelescopeOff command execution"
STR_TMC_OFF_EXEC = "TMC OFF command execution"
STR_TMC_ON_EXEC = "TMC ON command execution"
STR_ON_EXEC = "TelescopeOn command execution"
STR_RESOURCE_ALLOCATION_FAILED = "Resource allocation failed."
STR_TMC_STANDBY_EXEC = "TMC STANDBY command execution"
STR_TELESCOPE_STANDBY_EXEC = "Telescope STANDBY command execution"

# PROPERTIES DEFAULT VALUES
PROP_DEF_VAL_TM_MID_SA1 = "ska_mid/tm_subarray_node/1"
PROP_DEF_VAL_TM_MID_SA2 = "ska_mid/tm_subarray_node/2"
PROP_DEF_VAL_TM_MID_SA3 = "ska_mid/tm_subarray_node/3"
PROP_DEF_VAL_LEAF_NODE_PREFIX = "ska_mid/tm_leaf_node/d"
PROP_DEF_VAL_TM_MID_CSPSA_LN1 = "ska_mid/tm_leaf_node/csp_subarray01"
PROP_DEF_VAL_TM_MID_CSPSA_LN2 = "ska_mid/tm_leaf_node/csp_subarray02"
PROP_DEF_VAL_TM_MID_CSPSA_LN3 = "ska_mid/tm_leaf_node/csp_subarray03"
PROP_DEF_VAL_TM_MID_SDPSA_LN1 ="ska_mid/tm_leaf_node/sdp_subarray01"
PROP_DEF_VAL_TM_MID_SDPSA_LN2 = "ska_mid/tm_leaf_node/sdp_subarray02"
PROP_DEF_VAL_TM_MID_SDPSA_LN3 = "ska_mid/tm_leaf_node/sdp_subarray03"
PROP_DEF_VAL_TM_MID_DLN1 = "ska_mid/tm_leaf_node/d0001"
PROP_DEF_VAL_TM_MID_DLN2 = "ska_mid/tm_leaf_node/d0002"
PROP_DEF_VAL_TM_MID_DLN3 = "ska_mid/tm_leaf_node/d0003"
PROP_DEF_VAL_TM_MID_DLN4 = "ska_mid/tm_leaf_node/d0004"
PROP_DEF_VAL_TM_MID_CSPM_LN = "ska_mid/tm_leaf_node/csp_master"
PROP_DEF_VAL_TM_MID_SDPM_LN = "ska_mid/tm_leaf_node/sdp_master"
GET_DEVICE_LIST_TANGO_DB = "ska_mid/tm_leaf_node/d000*"


# INTEGERS
INT_SKA_LEVEL = 1
