image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive
# Temporarily pinning the versions for python-test and python-lint

stages:
  - lint
  - join-reports
  - build
  - test
  - publish
  - pages
  - scan
  - lifecycle

join_linting_reports:
  stage: join-reports
  script:
    - echo "This step is needed as the artifacts can't be passed in the same stage"
    - make join-lint-reports
  artifacts:
    paths:
      - build/
    when: always

include:
  # # # Helm Chart linting and Publish
  # Note: Commenting this part to Disable helm chart linting and Publish job from the pipeline
  # - project: 'ska-telescope/templates-repository'
  #   file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'
  # # Python packages build,lint, test and publish
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/python.gitlab-ci.yml"

  # # OCI images build and publish
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/oci-image.gitlab-ci.yml"

  # # Docs pages
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/docs.gitlab-ci.yml"

  # k8s steps
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/k8s.gitlab-ci.yml"

  # Release Automation
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/release.gitlab-ci.yml"

  # Create Gitlab CI badges from CI metrics
  # https://developer.skatelescope.org/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"

k8s-test:
  variables:
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
  before_script:
    - make cred SERVICE_ACCOUNT=$SERVICE_ACCOUNT
    - make k8s-install-chart
    - make k8s-wait
  script:
    - make k8s-test
    - make k8s-test MARK=restart_device_server
    - |
      if [[ "$CI_KEEP_NAMESPACE" != "true" ]]; then
        make k8s-uninstall-chart || true
        make k8s-delete-namespace || true
      fi;
    - '[ -f build/status ] || (echo "Something went wrong with the test (no build/status file); exit 1")'
    - exit $(cat build/status)

k8s-test-low:
  extends:
    - k8s-test
  variables:
    PYTANGO_GREEN_MODE: "futures"
    TELESCOPE: "SKA-low"
    CONFIG: "low"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-$CONFIG"
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-$CONFIG"
  before_script:
    - echo $TELESCOPE
    - make cred SERVICE_ACCOUNT=$SERVICE_ACCOUNT
    - make k8s-install-chart
    - make k8s-wait
  script:
    - make k8s-test
    - make k8s-test MARK=auto_recovery
    - |
      if [[ "$CI_KEEP_NAMESPACE" != "true" ]]; then
        make k8s-uninstall-chart || true
        make k8s-delete-namespace || true
      fi;
    - '[ -f build/status ] || (echo "Something went wrong with the test (no build/status file); exit 1")'
    - exit $(cat build/status)

  environment:
    name: test/$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-low
    auto_stop_in: 1 minute

stop-k8s-test-low:
  extends:
    - stop-k8s-test
  variables:
    CONFIG: "low"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-$CONFIG"
  script:
    - make k8s-uninstall-chart
    - kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,configmaps --all
    - make k8s-delete-namespace

docs-build-rtd:
  rules:
    - when: never
