[metadata]
description-file = README.rst

[aliases]
# Define `python setup.py test`
test=pytest

[coverage:run]
branch = True
source = src
data_file = code-coverage

[tool:pytest]
testpaths = tests
log_cli=true
log_level=DEBUG

addopts =
          --forked
          --json-report
          --json-report-file=build/reports/report.json
          --cov-branch
          --cov-report term
          --cov-report html:build/reports/htmlcov
          --cov-report xml:build/reports/code-coverage.xml
          --cov=ska_tmc_centralnode_mid
          --junitxml=build/reports/unit-tests.xml
          --verbose


console_output_style = progress
junit_family = legacy

filterwarnings =
    ignore::DeprecationWarning
