display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: true
  sub-system:
    ska-tango-base:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  retry:
  - "--tries=10"
  - "--sleep=5"
  DEBUG: 5678
  labels:
    app: ska-tmc-centralnode

ska-tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false
  itango:
    enabled: true
  jive:
    enabled: false

ska_tmc_simulators:
  enabled: true
  deviceServers:
    mocks:
      enabled: true



central_node:
  deviceServers:
    centralnode:
      enabled: true
      DishMasterIdentifier: "elt/master"

      
ska-taranta:
  enabled: false